# Generated by Django 5.0.4 on 2024-04-18 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=200, verbose_name="Pet Name"
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        default="", max_length=200, verbose_name="Pet Owner"
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        default="", max_length=200, verbose_name="Pet Breed"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vote_cutest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutest",
                        to="voting4h.pet",
                    ),
                ),
                (
                    "vote_people_choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people_choice",
                        to="voting4h.pet",
                    ),
                ),
                (
                    "vote_unique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unique",
                        to="voting4h.pet",
                    ),
                ),
            ],
        ),
    ]
