# Generated by Django 5.0.4 on 2024-04-18 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("voting4h", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="vote_cutest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cutest",
                to="voting4h.pet",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="vote_people_choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="people_choice",
                to="voting4h.pet",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="vote_unique",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unique",
                to="voting4h.pet",
            ),
        ),
    ]
