# Generated by Django 5.0.4 on 2024-07-20 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("voting4h", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ManualBallot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote_people_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voting4h.pet",
                    ),
                ),
            ],
        )
    ]
