# Generated by Django 5.1.11 on 2025-07-08 04:52

import django.db.models.deletion
from django.db import migrations, models


def initial_show_creation(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Show = apps.get_model("voting4h", "Show")
    Pet = apps.get_model("voting4h", "Pet")
    Ballot = apps.get_model("voting4h", "Ballot")
    my_show = Show.objects.create(
        name="2024",
        date=None,  # Set to None for no specific date
        location="Iowa City, IA",
        active=True,  # Set to True to make it the active show
    )
    Pet.objects.all().update(show=my_show)
    Ballot.objects.all().update(show=my_show)


class Migration(migrations.Migration):

    dependencies = [
        ("voting4h", "0002_manualballot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=200, verbose_name="Show Name"
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="Show Date"),
                ),
                (
                    "location",
                    models.CharField(
                        default="", max_length=200, verbose_name="Show Location"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=False, verbose_name="Active Show"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ballot",
            name="show",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ballots",
                to="voting4h.show",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="show",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="voting4h.show",
            ),
        ),
        migrations.RunPython(initial_show_creation),
    ]
