# Generated by Django 5.1.11 on 2025-07-12 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting4h", "0003_show_ballot_show_pet_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualballot",
            name="show",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manualballots",
                to="voting4h.show",
            ),
        ),
    ]
