# Generated by Django 5.1.11 on 2025-07-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting4h", "0005_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
